### ISSUE TITLE
It seems that it doesn't work

### ISSUE THREAD

**Issue by 3B4252** [instabotai/tiktokbot#2]
I run the run.py with no problems and opened Bluestacks, but the script doesn't do anything. Is it normal? Thanks.

**Comment by steffanjensen** [comment]
if you want to for example like videos, you need to be at the home screen for it to work..

**Comment by 3B4252** [comment]
Ehm man, I was at home screen. The output is "None" for everything, I thinks that I have problems with mouse coords. Sorry for disurbing but I made a tool for tiktok trend analysis and I wanted to add more functions like like, follow, comment. You know better than me that there a lot of problems with login, so I'm looking for an alternative way to do what I want.

**Comment by steffanjensen** [comment]
I think the issue is my images is taken with my screen-size and most likely we are not using the same. So the image detecting system is not able to detect the images. 

I will suggest you with the first image "home" which is shows "None".. Take a new picture of it "print-screen" and then replace it with mine..

and see if it's able to detect home now.. 

It should work.. let me know..

**Comment by steffanjensen** [comment]
https://github.com/instabotai/tiktokbot/blob/master/img/home.png

**Comment by 3B4252** [comment]
Ok I changed the .png and now the "home" function works. Now I have to change all the other pngs, but I think that everything will work. Thanks a lot for your help!

**Comment by steffanjensen** [comment]
Awesome let me know :)

Remember you can always make new functions :) such as comment, like and other stuff..

I will soon implement auto-reply for messages.
